project_name: jwt-cli

before:
  hooks:
    - go mod tidy

builds:
  - env: [ CGO_ENABLED=0 ]
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    id: tommytroen
    dir: .
    main: ./cmd/jwt-cli
    binary: jwt
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

checksum:
  name_template: 'checksums.txt'

archives:
  - format: tar.gz
    replacements:
      darwin: macOS
    files:
      - cosign.pub
      - dist/*.sig
    format_overrides:
      - goos: windows
        format: zip

sboms:
  - artifacts: archive

signs:
  - id: sign archives
    cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    args: ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    signature: "${artifact}.sig"
    artifacts: archive
  - id: sign checksum.txt
    cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    args: [ "sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}" ]
    signature: "${artifact}.sig"
    artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: 'Dependency updates'
      regexp: "^.*build(deps)[(\\w)]*:+.*$"
      order: 30
    - title: Other work
      order: 999

release:
  prerelease: allow
  draft: true
  github:
    owner: tommytroen
    name: jwt-cli
  header: |
    ## {{.ProjectName}} ({{ .Version }})
  footer: |
    ## {{.ProjectName}} 
    Those were the changes on {{ .Tag }}!
  extra_files:
    - glob: "cosign.pub"